GET http://localhost:3000/api/todos
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
GET http://localhost:3000/api/todos/5c5e5f78ff3f1e1abf3b76fa
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc

###
POST http://localhost:3000/api/todos
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc
Content-Type: application/x-www-form-urlencoded

name=makan&description=makan nasi goreng&dueDate=2019-12-31&owner=nasi&status=unfinished

###
PUT http://localhost:3000/api/todos/5c5e5f78ff3f1e1abf3b76fa
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc
Content-Type: application/x-www-form-urlencoded

name=makan&description=makan nasi goreng&dueDate=2019-12-31&owner=nasi&status=unfinished

###
DELETE http://localhost:3000/api/todos/5c5e5f45ff3f1e1abf3b76f9
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YzVlNWFlYzg4ZDBkYjE5NGE3Y2M2ZmIiLCJlbWFpbCI6ImFyaWVzcHRuQGdtYWlsLmNvbSIsIm5hbWUiOiJBcmllIFNlcHRpYW4iLCJnb29nbGVDbGllbnRJZCI6IjExNTE2Nzk1NzQ0MzMzODI2NTUwOCIsIl9fdiI6MCwiaWF0IjoxNTQ5Njg3NTMzfQ.zHLvjRpRRoLXiOjhz3etGyWGwp0JgxDvdRZi5JK9JYc
